app/views/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from ..forms import ProfessionalForm, LoginFrom, CustomerForm
from ..models import ProfessionalModel, UserRole, CustomerModel, AdminModel
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, current_user
from .. import db
import os
from werkzeug.utils import secure_filename
from flask import current_app

auth=Blueprint("auth", __name__)

@auth.route("choose-register")
def choose_register():
    return render_template("registration_choose.html")

@auth.route("professional/register", methods=["GET", "POST"])
def professional_register():
    form=ProfessionalForm()
    if(form.validate_on_submit()):
        exist_email=ProfessionalModel.query.filter_by(email=form.email.data).first()
        if(exist_email):
            flash("Email Already Exist", "danger")
            return render_template("professional/register.html", form=form)
        upload_folder = os.path.join(current_app.root_path, 'static/uploads/documents')
        if not os.path.exists(upload_folder):
            os.makedirs(upload_folder)
        document_path = None
        filename = None
        if(form.document.data):
            filename = secure_filename(form.document.data.filename)
            document_path = os.path.join(upload_folder, filename)
            form.document.data.save(document_path)

        new_professional=ProfessionalModel(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            gender=form.gender.data,
            email=form.email.data,
            phone_no=form.phone_no.data,
            password=generate_password_hash(form.password.data),
            service_name=form.service_name.data,
            experience=form.experience.data,
            document=filename,
            address=form.address.data,
            pin_code=form.pin_code.data,
            is_active=form.is_active.data,
            role=UserRole.PROFESSIONAL
        )
        db.session.add(new_professional)
        db.session.commit()
        flash("Registration successful!", "success")
        return redirect(url_for("auth.login"))
    return render_template("professional/register.html", form=form)

@auth.route("customer/register", methods=["GET", "POST"])
def customer_register():
    form=CustomerForm()
    if(form.validate_on_submit()):
        exist_email=CustomerModel.query.filter_by(email=form.email.data).first()
        if(exist_email):
            flash("Email Already Exist", "danger")
            return render_template("customer/register.html", form=form)
        new_customer= CustomerModel(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            gender=form.gender.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data),
            address=form.address.data,
            pin_code=form.pin_code.data,
            role=UserRole.CUSTOMER
        )
        db.session.add(new_customer)
        db.session.commit()
        flash("Registration successful!", "success")
        return redirect(url_for("public.home"))
    return render_template("customer/register.html", form=form) 

@auth.route("login", methods=["GET", "POST"])
def login():
    form=LoginFrom()
    if(form.validate_on_submit()):
        email=form.email.data
        password=form.password.data
        user=AdminModel.query.filter_by(email=email).first() or ProfessionalModel.query.filter_by(email=email).first() or CustomerModel.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            print("us", user.role, user.email)
            login_user(user)
            flash("Logged in Successfully", "success")
            if(user.role==UserRole.ADMIN):
                return redirect(url_for("admin.dashboard"))
            elif(user.role==UserRole.PROFESSIONAL):
                return redirect(url_for("professional.assign_work"))
            elif user.role==UserRole.CUSTOMER:
                return redirect(url_for("public.home"))
        else:
            flash("Invalid Email or Password", "danger")
    return render_template("login.html", form=form)

@auth.route("logout")
def logout():
    logout_user()
    flash("Logout out successfully!", "success")
    return redirect(url_for("auth.login"))

app/views/public.py
from flask import Blueprint, render_template, flash, redirect, url_for
public=Blueprint("public", __name__)
from ..models import ServiceModel, CustomerRequestModel
from ..forms import ServiceRequestForm
from flask_login import current_user, login_required
from .. import db

@public.route("")
def home():
    categories = [
        {"name": "AC Repair", "icon": "images/icons/air-conditioner.png"},
        {"name": "Mechanic", "icon": "images/icons/mechanic.png"},
        {"name": "Saloon", "icon": "images/icons/beauty-saloon.png"},
        {"name": "Plumbing", "icon": "images/icons/plumbing.png"},
        {"name": "Electrician", "icon": "images/icons/electrician.png"},
        {"name": "Painting", "icon": "images/icons/exhibition.png"},
        {"name": "Gardening", "icon": "images/icons/gardening.png"},
        {"name": "Makeup Artist", "icon": "images/icons/cosmetics.png"},
    ]
    return render_template("index.html", categories=categories)

@public.route("<category>")
def services_by_category(category):
    services = ServiceModel.query.filter_by(category=category).all()
    return render_template("public/services_by_category.html", category=category, services=services)

@public.route("<category>/<service_id>", methods=["GET", "POST"])
@login_required
def service_request(category,service_id):
    service=ServiceModel.query.get_or_404(service_id)
    form=ServiceRequestForm()
    if(form.validate_on_submit()):
        new_request = CustomerRequestModel(
            customer_id=current_user.id,
            service_id=service.id,
            preferred_date=form.preferred_date.data,
            preferred_time=form.preferred_time.data,
            additional_notes=form.additional_notes.data,
            address=form.address.data,
        )
        db.session.add(new_request)
        db.session.commit()
        flash("Your request has been placed successfully!", "success")
        return redirect(url_for("public.home"))
    return render_template("public/service_request.html",form=form, category=category, service_id=service_id)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>{%block title %} {%endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('public.home')}}">
          {%if current_user.is_authenticated and current_user.role.value=='Admin'%}
              Welcome to Admin
          {%elif current_user.is_authenticated and current_user.role.value=='Professional'%}
              Welcome to Professional
          {%else%}
              Welcome to Customer
          {%endif%}
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if request.endpoint == 'public.home' %}active fw-semibold{% endif %}" aria-current="page" href="{{url_for('public.home')}}">Home</a>
            </li>
           {%if current_user.is_authenticated and current_user.role.value=='Customer'%}
                <li class="nav-item">
                  <a class="nav-link {% if request.endpoint == 'customer.orders' %}active fw-semibold{% endif %}" href="{{url_for('customer.orders')}}">My Orders</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.endpoint == 'customer.summary' %}active fw-semibold{% endif %}" href="{{url_for('customer.summary')}}">Summary</a>
                </li>
           {%endif%}
           {%if current_user.is_authenticated and current_user.role.value=='Professional'%}
           <li class="nav-item">
             <a class="nav-link {% if request.endpoint == 'professional.assign_work' %}active fw-semibold{% endif %}" href="{{url_for('professional.assign_work')}}">Assign Work</a>
           </li>
           <li class="nav-item">
            <a class="nav-link {% if request.endpoint == 'professional.summary' %}active fw-semibold{% endif %}" href="{{url_for('professional.summary')}}">Summary</a>
          </li>
          {%endif%}
           {%if current_user.is_authenticated and current_user.role.value=='Admin'%}
           <li class="nav-item">
            <a class="nav-link {% if request.endpoint == 'admin.dashboard' %}active fw-semibold{% endif %}" href="{{url_for('admin.dashboard')}}">Dashboard</a>
          </li>
              <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'admin.services' %}active fw-semibold{% endif %}" href="{{url_for('admin.services')}}">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'admin.orders' %}active fw-semibold{% endif %}" href="{{url_for('admin.orders')}}">Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.endpoint == 'admin.professionals' %}active fw-semibold{% endif %}" href="{{url_for('admin.professionals')}}">Professionals</a>
              </li>
            {%endif%}
          </ul>
            {%if current_user.is_authenticated %}
               <div class="log-user-box">
                  <a class="nav-link profile" href="{{get_profile_url()}}">Hi, {{current_user.first_name.capitalize()}}</a>
                  <button type="button" class="btn btn-danger"> 
                    <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                  </button>
               </div>
            {%else%}
                <button type="button" class="btn btn-outline-primary"> 
                    <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                </button>
                <button type="button" class="btn btn-primary ms-2">
                    <a class="nav-link" href="{{url_for('auth.choose_register')}}">Register</a>
                </button>
            {%endif%}
        </div>
      </div>
    </nav>
    <div class="alert-box">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    </div>

    <div class="container">{%block content %} {%endblock %}</div>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"
  ></script>  
  <script src="{{ url_for('static', filename='script/bootstrap.js') }}"></script>
</html>

app/templates/index.html
{% extends "base.html" %} 

{% block title %} Home - Household {% endblock %}

{%block content%}
<div class="container mt-3">
    <h3 align="center">Looking For!</h3>
    <div class="services">
          {% for category in categories %}
              <a href="{{ url_for('public.services_by_category', category=category.name) }}" class="text-decoration-none">
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <img class="icon" src="{{ url_for('static', filename=category.icon) }}" alt="App Icon">
                    <h5 class="card-title">{{category.name}}</h5>
                  </div>
                </div>
              </a>
          {% endfor %}  
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %} 

{% block title %} Login - Household  {% endblock %}

{%block content%}
<div class="container my-5 max-width-900">
    <h2 align="center">Log In</h2>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class_="form-control", type="email", placeholder="name@example.com") }}
          </div>
          <div class="mb-3">
            {{ form.password.label(class="form-label") }}
            {{ form.password(class_="form-control", placeholder="********") }}
          </div>
          <div class="mb-3 mt-3 d-grid gap-2">
            <button type="submit" class="btn btn-primary w-full">Submit</button>
        </div>
    </form>
    <h6 align="center">New User? <a href="{{url_for('auth.choose_register')}}">Sign Up!</a></h6>
</div>
{% endblock %}

app/templates/registration_choose.html
{% extends "base.html" %} 

{% block title %} Register - Household  {% endblock %}

{%block content%}
<div class="container my-5 max-width-900">
    <h2 align="center">Select Registration</h2>
  
   <div class="mb-3 mt-3 d-grid gap-2">
    <button class="btn btn-primary">
        <a class="nav-link" href="{{url_for('auth.customer_register')}}">Customer Register</a>
    </button>
    <button class="btn btn-primary">
        <a class="nav-link" href="{{url_for('auth.professional_register')}}">Professional Register</a>
    </button>
</div>
</div>
{% endblock %}